# Generated by Django 5.2.3 on 2025-06-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="user", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
