# Generated by Django 5.2.3 on 2025-06-20 02:35

from django.db import migrations, models
import re


def generate_unique_usernames(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        if user.username:
            continue
        base = user.email.split("@")[0]
        base = re.sub(r"[^a-zA-Z0-9_]+", "", base)
        candidate = base or "user"
        suffix = 1
        while User.objects.filter(username=candidate).exists():
            candidate = f"{base}{suffix}"
            suffix += 1
        user.username = candidate
        user.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
        migrations.RunPython(generate_unique_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
