version: "3.9"
services:
  web:
    build: ./backend
    command: gunicorn server.wsgi:application -b 0.0.0.0:8000 --workers 4
    env_file: backend/.env
    depends_on:
      - redis
  redis:
    image: redis:7
  worker:
    build: ./backend
    command: celery -A server worker -l info
    env_file: backend/.env
    depends_on:
      - redis
  nginx:
    image: nginx:1.25
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
