# Generated by Django 5.2.3 on 2025-06-20 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shame", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="herdpost",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_herd_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
