# Generated by Django 5.2.3 on 2025-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_voicejournal"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicejournal",
            name="playback_audio_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
