# Generated by Django 5.2.3 on 2025-06-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_herd"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="current_mood",
            field=models.CharField(default="neutral", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="mood_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
