name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r backend/requirements.txt
      - name: Run tests
        run: |
          . venv/bin/activate
          make test-backend
      - name: Lint
        run: |
          . venv/bin/activate
          make lint-backend
